version: 2
updates:
  - package-ecosystem: "npm" # ou "yarn", "pip", "maven", etc.
    directory: "/" # onde está o package.json
    schedule:
      interval: "daily" # ou "weekly", "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix"
