name: Verificação de Vulnerabilidades em Dependências Node.js

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x" # Substitua pela versão do Node.js que você usa

      - name: Instalar dependências
        run: npm install

      - name: Rodar auditoria de segurança
        run: npm audit --audit-level=high
