name: Verificação de Vulnerabilidades Docker

on: [pull_request]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instala Trivy
        run: sudo apt-get install -y wget && wget https://github.com/aquasecurity/trivy/releases/download/v0.30.0/trivy_0.30.0_Linux-64bit.deb && sudo dpkg -i trivy_0.30.0_Linux-64bit.deb
      - name: Verifica vulnerabilidades no Dockerfile
        run: trivy image --no-progress --exit-code 1 .
