name: Build and Test Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Hadolint
        run: |
          curl -sSL https://github.com/hadolint/hadolint/releases/download/v2.8.0/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint

      - name: Run Hadolint on Dockerfile
        run: hadolint Dockerfile

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t juice-shop .

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 --name juice-shop-container juice-shop

      - name: Test Docker container
        run: |
          curl --silent --fail http://localhost:3000 || exit 1
